# Generated by Django 3.1 on 2020-09-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200909_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takenquiz',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
